version: '3'
services:
  db:
    build:
      dockerfile: ./docker/db/Dockerfile
      context: .
    restart: always
    ports:
      - "33666:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codingtest
      MYSQL_USER: codingtest
      MYSQL_PASSWORD: password
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
      - "db"
    environment:
      WAIT_HOSTS: db:3306